// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiMun.Data;

#nullable disable

namespace ServiMun.Migrations
{
    [DbContext(typeof(TributoMunicipalContext))]
    [Migration("20241021020406_AgregadoDatosServicio")]
    partial class AgregadoDatosServicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ServiMun.Models.Contribuyente", b =>
                {
                    b.Property<int>("IdContribuyente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContribuyente"), 1L, 1);

                    b.Property<string>("ApellidoNombreContribuyente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DomicilioCalleContribuyente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DomicilioNumeroContribuyente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimientoContribuyente")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroDocumentoContribuyente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("SexoContribuyente")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TelefonoContribuyente")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdContribuyente");

                    b.HasIndex("NumeroDocumentoContribuyente")
                        .IsUnique();

                    b.ToTable("Contribuyentes");
                });

            modelBuilder.Entity("ServiMun.Models.PadronBoleta", b =>
                {
                    b.Property<int>("IdBoleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoleta"), 1L, 1);

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Importe2")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("NumeroPadron")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vencimiento2")
                        .HasColumnType("datetime2");

                    b.HasKey("IdBoleta");

                    b.HasIndex("NumeroPadron");

                    b.ToTable("PadronBoletas");
                });

            modelBuilder.Entity("ServiMun.Models.PadronContribuyente", b =>
                {
                    b.Property<int>("IdContribuyente")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdTributoMunicipal")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroPadron")
                        .HasColumnType("int");

                    b.HasKey("IdContribuyente", "IdTributoMunicipal");

                    b.HasIndex("IdTributoMunicipal");

                    b.ToTable("PadronContribuyentes");
                });

            modelBuilder.Entity("ServiMun.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"), 1L, 1);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sintetico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("ServiMun.Models.ServicioBoleta", b =>
                {
                    b.Property<int>("IdBoletaServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoletaServicio"), 1L, 1);

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Importe2")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("NumeroServicio")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vencimiento2")
                        .HasColumnType("datetime2");

                    b.HasKey("IdBoletaServicio");

                    b.HasIndex("NumeroServicio");

                    b.ToTable("ServicioBoletas");
                });

            modelBuilder.Entity("ServiMun.Models.ServicioCliente", b =>
                {
                    b.Property<int>("IdContribuyente")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroCliente")
                        .HasColumnType("int");

                    b.Property<int>("NumeroServicio")
                        .HasColumnType("int");

                    b.Property<int>("NumeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("IdContribuyente", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("ServicioClientes");
                });

            modelBuilder.Entity("ServiMun.Models.TributoMunicipal", b =>
                {
                    b.Property<int>("IdTributo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTributo"), 1L, 1);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreTributo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sintetico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdTributo");

                    b.ToTable("TributosMunicipales");
                });

            modelBuilder.Entity("ServiMun.Models.PadronBoleta", b =>
                {
                    b.HasOne("ServiMun.Models.PadronContribuyente", "PadronContribuyente")
                        .WithMany("PadronBoletas")
                        .HasForeignKey("NumeroPadron")
                        .HasPrincipalKey("NumeroPadron")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PadronContribuyente");
                });

            modelBuilder.Entity("ServiMun.Models.PadronContribuyente", b =>
                {
                    b.HasOne("ServiMun.Models.Contribuyente", "Contribuyente")
                        .WithMany("PadronContribuyentes")
                        .HasForeignKey("IdContribuyente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiMun.Models.TributoMunicipal", "TributoMunicipal")
                        .WithMany("PadronContribuyentes")
                        .HasForeignKey("IdTributoMunicipal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");

                    b.Navigation("TributoMunicipal");
                });

            modelBuilder.Entity("ServiMun.Models.ServicioBoleta", b =>
                {
                    b.HasOne("ServiMun.Models.ServicioCliente", "ServicioCliente")
                        .WithMany("ServicioBoletas")
                        .HasForeignKey("NumeroServicio")
                        .HasPrincipalKey("NumeroServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicioCliente");
                });

            modelBuilder.Entity("ServiMun.Models.ServicioCliente", b =>
                {
                    b.HasOne("ServiMun.Models.Contribuyente", "Contribuyente")
                        .WithMany("ServicioClientes")
                        .HasForeignKey("IdContribuyente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiMun.Models.Servicio", "Servicio")
                        .WithMany("ServicioClientes")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ServiMun.Models.Contribuyente", b =>
                {
                    b.Navigation("PadronContribuyentes");

                    b.Navigation("ServicioClientes");
                });

            modelBuilder.Entity("ServiMun.Models.PadronContribuyente", b =>
                {
                    b.Navigation("PadronBoletas");
                });

            modelBuilder.Entity("ServiMun.Models.Servicio", b =>
                {
                    b.Navigation("ServicioClientes");
                });

            modelBuilder.Entity("ServiMun.Models.ServicioCliente", b =>
                {
                    b.Navigation("ServicioBoletas");
                });

            modelBuilder.Entity("ServiMun.Models.TributoMunicipal", b =>
                {
                    b.Navigation("PadronContribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
